[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_airdrop_dapp = "5f9SViZQr76U5V7sHpzBRrBEJ6ypjd4gfQWPdM2Rta7T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pranav/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
